FROM alpine:latest
LABEL maintainer="developer@catalyst.net.nz"

RUN apk --no-cache add --virtual native-deps \
  g++  \
  gcc \
  libgcc \
  libstdc++ \
  linux-headers 

WORKDIR /usr/local/app

ADD https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz .     
RUN  tar xf android-sdk_r24.4.1-linux.tgz && \     
  rm -f android-sdk_r24.4.1-linux.tgz

