FROM alpine:latest
LABEL maintainer="developer@catalyst.net.nz"

RUN apk --no-cache add \
  g++  \
  gcc \
  libgcc \
  libstdc++ \
  linux-headers 

WORKDIR /usr/local/app

RUN apk --no-cache add --virtual native-deps wget && \
  wget https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz && \     
  tar xf android-sdk_r24.4.1-linux.tgz && \     
  rm -f android-sdk_r24.4.1-linux.tgz && \
  apk del native-deps


