FROM ubuntu:latest

RUN apt-get update
#RUN apt-get install -y curl
RUN apt-get install -y dpkg-sig
RUN apt-get install -y libcap-dev
RUN apt-get install -y libsqlite3-dev
RUN apt-get install -y mercurial
RUN apt-get install -y reprepro
RUN rm -rf /var/lib/apt/lists/*
