FROM ubuntu:16.04
LABEL maintainer="developer@catalyst.net.nz"


RUN apt-get update && apt-get install -yy \
    gcc-multilib \
    lib32stdc++6 \
    lib32z1 
RUN rm -fr /var/lib/apt/lists/*


WORKDIR /usr/local # Set up android SDK 
ADD https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz /usr/local

RUN cd /usr/local && tar xf android-sdk_r24.4.1-linux.tgz &&  rm -f android-sdk_r24.4.1-linux.tgz
